using Microsoft.Extensions.Logging;
using SquareDMS.DatabaseAccess;
using SquareDMS.DataLibrary;
using SquareDMS.DataLibrary.Entities;
using SquareDMS.DataLibrary.ProcedureResults;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SquareDMS.Core.Dispatchers
{
    /// <summary>
    /// Mostly passes the operations from the
    /// UserController to the database. Does some checks 
    /// regarding the Credentials.
    /// </summary>
    public class UserDispatcher : Dispatcher
    {
        private readonly ISquareDb _squareDb;
        private readonly ILogger _logger;

        /// <summary>
        /// 
        /// </summary>
        public UserDispatcher(ISquareDb squareDb, ILogger<UserDispatcher> logger)
        {
            _squareDb = squareDb;
            _logger = logger;
        }

        /// <summary>
        /// Validates the given credentials. Checks if the password matches the one
        /// stored in the database. Also checks if the username is valid and has a matching
        /// userId in the database. Returns null if the credentials are invalid or wrong.
        /// </summary>
        public async Task<User> CheckUserCredentialAsync(Credential userCredential)
        {
            // gets the first result in the resultset, its only one user.
            var user = (await _squareDb.RetrieveUserByUserNameAsync(userCredential.UserName)).Resultset.FirstOrDefault();

            // user not found in db
            if (user is null)
            {
                _logger.LogInformation("Username was not found in the database (Username: {0})", userCredential.UserName);
                return null;
            }

            var pwsMatch = Credential.MatchPasswordHashes(user.PasswordHash, userCredential.HashPassword());

            // passwords dont match
            if (!pwsMatch)
            {
                _logger.LogInformation("Passwords didnt match for Username: {0})", userCredential.UserName);
                return null;
            }

            return user;
        }

        #region CRUD-Operationen
        /// <summary>
        /// Creates a new user in the database or returns an errorcode if this
        /// operation faulty. Also creates a group for the user.
        /// </summary>
        /// <param name="id">User that creates the user</param>
        /// <param name="user">User to be created</param>
        /// <returns>ManipulationResult with errorCode</returns>
        public async Task<ManipulationResult<User>> CreateUserAndGroupAsync(int id, User user)
        {
            // create user
            var userCreationResult = await _squareDb.CreateUserAsync(id, user);
            var userId = userCreationResult.ManipulatedEntity.Id;

            // username already exists
            if (userId is null)
                return userCreationResult;

            // create group
            var groupCreationResult = await _squareDb.CreateGroupAsync(id, new Group()
            {
                Name = $"UserID: {userId.Value} Group",
                Description = "Autogenerated group for a user"
            });
            var groupId = groupCreationResult.ManipulatedEntity.Id;

            // put new user in the created group
            var groupMemberCreationResult = await _squareDb.CreateGroupMemberAsync(id, new GroupMember(groupId, userId));

            // collect all operations
            List<Operation> operations = new List<Operation>();
            operations.AddRange(userCreationResult.Operations);
            operations.AddRange(groupCreationResult.Operations);
            operations.AddRange(groupMemberCreationResult.Operations);

            // creation of all entities successful
            if (userCreationResult.ErrorCode == 0 && groupCreationResult.ErrorCode == 0 &&
                groupMemberCreationResult.ErrorCode == 0)
            {
                return new ManipulationResult<User>(0, userCreationResult.ManipulatedEntity, operations.ToArray());
            }

            return new ManipulationResult<User>(130, userCreationResult.ManipulatedEntity, operations.ToArray());
        }

        /// <summary>
        /// Gets the users that match the params.
        /// </summary>
        public async Task<RetrievalResult<User>> RetrieveUsersAsync(int id, int? userId = null,
            string lastName = null, string firstName = null,
            string userName = null, string email = null,
            bool? active = null)
        {
            return await _squareDb.RetrieveUserAsync(id, userId, lastName, firstName, userName, email, active);
        }

        /// <summary>
        /// Updates a user.
        /// </summary>
        public async Task<ManipulationResult<User>> UpdateUserAsync(int id, int updateUserId, User patchedUser)
        {
            return await _squareDb.UpdateUserAsync(id, updateUserId,
                patchedUser.LastName, patchedUser.FirstName, patchedUser.Email,
                patchedUser.PasswordHash, patchedUser.Active);
        }

        /// <summary>
        /// Deletes a user.
        /// </summary>
        public async Task<ManipulationResult<User>> DeleteUserAsync(int id, int deleteUserId)
        {
            return await _squareDb.DeleteUserAsync(id, deleteUserId);
        }
        #endregion
    }
}
